version: 2

sources:
  - name: dbt_practice
    database: primal-stock-471621-b6
    schema: growth_analytics
    tables:
      - name: synthetic_daily_revenue

  - name: marketing_raw
    database: primal-stock-471621-b6
    schema: growth_analytics
    tables:
      - name: profiles
      - name: payments
      - name: activity